<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2186e2ef-0241-4e18-882c-ab36c2d0be2e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\01.Domain\01.Domain.csproj" />
    <ProjectReference Include="..\02.Application\02.Application.csproj" />
    <ProjectReference Include="..\EShop.Infrastructure.Identity\EShop.Infrastructure.Identity.csproj" />
    <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
