<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_02.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="AdminAgg\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MassTransit" Version="9.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\01.Domain\01.Domain.csproj" />
    <ProjectReference Include="..\EShop.Shared.Application\EShop.Shared.Application.csproj" />
  </ItemGroup>

</Project>
